models:
- name: clientes
  enabled: true
  materialized: table
  description: Tabela de clientes
  columns:
  - name: id_cliente
    description: ID do cliente
    tests:
    # - unique
    - not_null
  - name: nome_completo
    description: Nome completo do cliente
    tests:
    - not_null
  - name: primeiro_pedido
    description: Primeiro pedido do cliente
  - name: pedido_mais_recente
    description: Pedido mais recente do cliente
  - name: pagamento_total
    description: Valor total do pagamento do cliente
- name: pedidos
  enabled: true
  materialized: table
  description: Tabela de pedidos
  columns:
  - name: id_pedido
    description: ID do pedido
    tests:
    # - unique
    - not_null
  - name: id_cliente
    description: ID do cliente que fez o pedido
    tests:
    - not_null
  - name: data_pedido
    description: Data do pedido
    tests:
    - not_null
  - name: status
    description: 'Status do pedido (ex: ''pending'', ''completed'', ''cancelled'')'
    tests:
    - not_null
  - name: credit_card_amount
    description: Amount of the order (BRL) paid for by credit card
  - name: coupon_amount
    description: Amount of the order (BRL) paid for by coupon
  - name: bank_transfer_amount
    description: Amount of the order (BRL) paid for by bank transfer
  - name: gift_card_amount
    description: Amount of the order (BRL) paid for by gift card

- name: clientes_analitico
  description: "Tabela analítica com métricas agregadas por cliente, como total de pedidos, ticket médio e categoria."
  columns:
    - name: id_cliente
      description: "Identificador único do cliente"
      tests:
        - not_null

    - name: primeira_compra
      description: "Data da primeira compra do cliente"
      tests:
        - not_null

    - name: ultima_compra
      description: "Data da última compra do cliente"
      tests:
        - not_null

    - name: total_pedidos
      description: "Total de pedidos feitos pelo cliente"
      tests:
        - not_null
        - dbt_expectations.expect_column_values_to_be_between:
            min_value: 0

    - name: intervalo_compras
      description: "Dias distintos de compra menos 1"
      tests:
        - dbt_expectations.expect_column_values_to_be_between:
            min_value: 0

    - name: total_pago
      description: "Soma total de todos os pagamentos feitos pelo cliente"
      tests:
        - not_null
        - dbt_expectations.expect_column_values_to_be_between:
            min_value: 0

    - name: ticket_medio
      description: "Valor médio gasto por pedido"
      tests:
        - dbt_expectations.expect_column_values_to_be_between:
            min_value: 0

    - name: total_pagamentos
      description: "Número de pagamentos registrados para o cliente"
      tests:
        - dbt_expectations.expect_column_values_to_be_between:
            min_value: 0

    - name: forma_pagamento_preferida
      description: "Forma de pagamento mais frequente do cliente"